code --install-extension adpyke.codesnap
code --install-extension AndenetAlexander.vim-cheatsheet
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension calebporzio.better-phpunit
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension DivyanshuAgrawal.competitive-programming-helper
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension frhtylcn.pythonsnippets
code --install-extension hbenl.vscode-test-explorer
code --install-extension hoovercj.vscode-settings-cycler
code --install-extension jock.svg
code --install-extension johnpapa.vscode-peacock
code --install-extension junstyle.php-cs-fixer
code --install-extension mdickin.markdown-shortcuts
code --install-extension mikestead.dotenv
code --install-extension MisterJ.vue-volar-extention-pack
code --install-extension moalamri.inline-fold
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension Nuxt.mdc
code --install-extension oijaz.unicode-latex
code --install-extension Prisma.prisma
code --install-extension rangav.vscode-thunder-client
code --install-extension recca0120.vscode-phpunit
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.vue-vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sleistner.vscode-fileutils
code --install-extension steoates.autoimport
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension Vue.volar
code --install-extension Vue.vscode-typescript-vue-plugin
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xdebug.php-debug
code --install-extension xdebug.php-pack
code --install-extension zhuangtongfa.material-theme
code --install-extension znck.vue
code --install-extension zobo.php-intellisense
